### ISSUE TITLE
time rotate auditlog index

### ISSUE THREAD

**Issue by rptete** [floragunncom/search-guard-module-auditlog#10] opened 2017-04-20 08:34 UTC
Hi,

Like Alexnav, i would like that we could include an timestamp in the name of auditlog's indices , or other way to delete old  auditlog indices fastly.

thanks

**Comment by floragunn** [comment] 2017-04-21 12:04
This seems to be pretty much like a duplicate of https://github.com/floragunncom/search-guard-module-auditlog/issues/9

**Closed as completed** 2017-04-21 12:06 UTC
